---

- hosts: all
  remote_user: root
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

  roles:
  - common
  - users
  - swap

- hosts: docker
  remote_user: root
  roles:
  - docker
