---

- name: Add Docker group
  group:
    name: docker

- name: Ruslan
  user:
    name: ruslan
    groups: docker
    home: /home/ruslan
    password: "{{ ruslan_shadow }}"
    shell: /bin/bash

- name: Ssh key ruslan
  authorized_key:
    user: ruslan
    key: https://raw.githubusercontent.com/ruslan2k/public-files/master/docker/centos-ssh/id_rsa.pub

- name: Add id_rsa
  template: src=id_rsa dest=/home/ruslan/.ssh/id_rsa
