---

- name: Install Dev soft
  yum: name={{ item }} state=present
  with_items:
  - "@Development tools"
  - xorg-x11-fonts-Type1 # for virtual box
  - vim-enhanced
  - screen
  - strace
  - tmux
  - git

- name: Install Python libs
  yum: name={{ item }} state=present
  with_items:
  - python-pip
  - python-devel

- name: Update pip
  pip: name=pip state=latest

- name: Install python pkgs
  pip: name={{ item }}
  with_items:
  - sshpubkeys
  - ansible
