---

- name: Debug
  debug: var=test_var

- name: Install common pkgs
  yum: name={{ item }} state=present
  with_items:
  - libselinux-python
  - epel-release
  - bind-utils
  - traceroute
  - wget

- name: Copy root cert
  copy: content={{aptinfo_root_pem_cert}} mode=0644
    dest=/etc/pki/ca-trust/source/anchors/aptinfo-root.pem
  notify: [update-ca-trust]

- name: Copy my_ip script
  template: src=tell_my_ip.sh.j2 dest=/usr/local/bin/tell_my_ip.sh
    mode=0750 owner=nobody group=root

- name: Add DNS IP script to cron
  cron: name="Tell ip" minute="*/5" user=nobody
    job="sh /usr/local/bin/tell_my_ip.sh &>/dev/null"
