---

- name: Install common pkgs
  yum: name={{ item }}
  with_items:
  - libselinux-python
  - epel-release
  - bind-utils
  - traceroute
  - logwatch
  - wget

- name: Disable set-hostname
  command: scarletctl disable set-hostname
  ignore_errors: yes

- name: Install Cron
  yum: name=cronie

- name: Start crond
  service: name=crond enabled=yes state=started

- name: Copy root cert
  copy: content={{aptinfo_root_pem_cert}} mode=0644
    dest=/etc/pki/ca-trust/source/anchors/aptinfo-root.pem
  notify: [update-ca-trust]

- name: Copy my_ip script
  template: src=tell_my_ip.sh.j2 dest=/usr/local/bin/tell_my_ip.sh
    mode=0750 owner=nobody group=root

- name: Run DNS script at start
  cron: name="Tell ip on start" special_time=reboot user=nobody
    job="sh /usr/local/bin/tell_my_ip.sh &>/dev/null"
- name: Add DNS IP script to cron
  cron: name="Tell ip" minute="*/5" user=nobody
    job="sh /usr/local/bin/tell_my_ip.sh &>/dev/null"

- name: Forward root email
  lineinfile: "dest=/etc/aliases insertafter=EOF line='root: {{ root_email }}'"
- name: Update aliases
  shell: "newaliases"
  ignore_errors: yes

#- name: debug
#  template: src=vars.j2 dest=/root/debug.txt

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname backup=yes
  

